changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Packaging and wheels
      labels:
        - packaging
        - wheels
        - build
        - cibuildwheel
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Maintenance
      labels:
        - maintenance
        - ci
        - github-actions
    - title: Other changes
      labels:
        - "*"
